#!/usr/bin/env bash
# pings an IP address passed as an argument.


# Check if an argument is passed
if [ -z "$1" ]; then
  echo "Usage: 5-is_the_host_on_the_network $0 "
  exit 1
fi

# Get the IP address from the argument
IP_ADDRESS=$1

# Ping the IP address 5 times
ping -c 5 "$IP_ADDRESS"
